data_folder: /Users/lorenlugosch/AndroidStudioProjects/timers-and-such-backup
train_csv: with-gestures.csv
batch_size: 2
train_dataloader_opts:
    # num_workers: 2
    batch_size: !ref <batch_size>

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: 16000
    n_fft: 512
    n_mels: 80
